{% set version = '2.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-twang
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/twang_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/twang/twang_{{ version }}.tar.gz
  sha256: fc355527c57e4f6e0f60d26d7c690c4475fcd5fb165d125fea7cc6b9fafc4ce5

build:
  merge_build_host: True           # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                    # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrixmodels
    - r-data.table
    - r-gbm >=1.5_3
    - r-ggplot2
    - r-lattice
    - r-latticeextra
    - r-survey
    - r-xgboost
    - r-xtable
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrixmodels
    - r-data.table
    - r-gbm >=1.5_3
    - r-ggplot2
    - r-lattice
    - r-latticeextra
    - r-survey
    - r-xgboost
    - r-xtable

test:
  commands:
    - $R -e "library('twang')"           # [not win]
    - "\"%R%\" -e \"library('twang')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=twang
  license: GPL-3.0-only
  summary: Provides functions for propensity score estimating and weighting, nonresponse weighting,
    and diagnosis of the weights.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: twang
# Version: 2.5
# Date: 2021-10-20
# Title: Toolkit for Weighting and Analysis of Nonequivalent Groups
# Author: Matthew Cefalu <Matthew_Cefalu@rand.org>, Greg Ridgeway, Dan McCaffrey, Andrew Morral, Beth Ann Griffin, and Lane Burgette
# Maintainer: Matthew Cefalu <Matthew_Cefalu@rand.org>
# Depends: R (>= 2.10)
# Imports: gbm (>= 1.5-3), survey, xtable, lattice, latticeExtra, MatrixModels, data.table, ggplot2, xgboost
# Suggests: knitr
# Description: Provides functions for propensity score estimating and weighting, nonresponse weighting, and diagnosis of the weights.
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# NeedsCompilation: yes
# Repository: CRAN
# VignetteBuilder: knitr
# RoxygenNote: 7.1.1
# Packaged: 2021-10-20 15:10:41 UTC; Matt
# Date/Publication: 2021-10-25 12:50:02 UTC
